# Generated by Django 5.1.3 on 2024-11-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosCondicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_medicion', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('circunferencia_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nivel_condicion_fisica', models.CharField(choices=[('novato', 'Novato'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50)),
                ('objetivo_entrenamiento', models.CharField(max_length=100)),
                ('historial_lesiones', models.TextField(blank=True, null=True)),
                ('frecuencia_entrenamiento', models.PositiveIntegerField()),
                ('nivel_actividad_diaria', models.CharField(choices=[('sedentario', 'Sedentario'), ('activo', 'Activo'), ('muy_activo', 'Muy Activo')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_condicion', to='landing.usuario')),
            ],
        ),
    ]
