# Generated by Django 5.1.3 on 2024-11-10 21:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_validez', models.DateField()),
                ('tipo_entrenamiento', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('fuerza', 'Fuerza'), ('resistencia', 'Resistencia'), ('cardio', 'Cardio'), ('movilidad', 'Movilidad'), ('tecnica', 'Técnica')], max_length=50)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_entrenamiento', to='landing.atletas')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.PositiveIntegerField()),
                ('unidad_repeticion', models.CharField(choices=[('repeticiones', 'Repeticiones'), ('tiempo', 'Tiempo (segundos)'), ('peso', 'Peso (kg)')], default='repeticiones', max_length=20)),
                ('series', models.PositiveIntegerField()),
                ('intensidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('maxima', 'Máxima')], max_length=50)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.ejercicio')),
                ('plan_entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='landing.planentrenamiento')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo_entrenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='landing.tipoentrenamiento'),
        ),
    ]
