# Generated by Django 5.1.3 on 2024-11-10 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_ejercicio_tipoentrenamiento_planentrenamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planentrenamiento',
            name='tipo_entrenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='landing.tipoentrenamiento'),
        ),
    ]
