# Generated by Django 5.1.3 on 2024-11-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Atleta',
        ),
        migrations.RenameField(
            model_name='datoscondicion',
            old_name='usuario',
            new_name='atleta',
        ),
    ]
